# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

calc_indicatC <- function(Y, threshold, custom = NULL) {
    .Call(`_SAEforest_calc_indicatC`, Y, threshold, custom)
}

smear_fun <- function(popSize, unit_preds, oob_res, threshold) {
    .Call(`_SAEforest_smear_fun`, popSize, unit_preds, oob_res, threshold)
}

